### ISSUE TITLE
git-annex: add datalad/git-annex:release method

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#101]
If I got it right we have
- `datalad/git-annex` -- most recent (could be daily snapshot) build
- `datalad/git-annex:tested` -- as above but the one which passed tests
so there is no way to install the most recent one (or that version if specified) from https://github.com/datalad/git-annex/releases as now should be `10.20220322`.

Might be handy to be used in datalad testing instead of `snapshot` which has odd versioning (see https://git-annex.branchable.com/forum/standalone_tarballs_for_specific_versions/#comment-d15b771fb5d23ce0c8dfb7f1c25064c5)

**Comment by jwodder** [comment]
@yarikoptic If the latest release lacks artifacts for the OS (as the current one does), should the script error or fall back to the most recent release that does have artifacts?
