### ISSUE TITLE
on M1 Mac, make sure "rosetta" is installed

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#103]
I have succeeded to follow instructions and install git-annex using datalad-installer from a dmg on our M1 . More detail is in https://github.com/datalad-handbook/book/pull/834/files#r853129160 .  The critical point is making sure that rosetta is installed

- if on M1 -- check if rosetta is installed,
  - if not installed, run `/usr/sbin/softwareupdate --install-rosetta --agree-to-license` or alike (may be prompting user)
- the rest should be standard

Later we might disable whenever there would be a native build for M1.

**Comment by jwodder** [comment]
@yarikoptic I need to know how to identify an M1 Mac.  I assume I just need to check for the correct string from `platform.architecture()` or `platform.machine()`, but when I tried to SSH to the M1 Mac (at datalad@207.254.40.152) to see what the values are there, the connection was immediately closed.

**Comment by yarikoptic** [comment]
not sure what is about the immediate closing of connection. I had similar for my attempt to login as administrator today, didn't figure it out.  How to troubleshoot on mac?

meanwhile:

```
$> ssh datalad@207.254.40.152
Last login: Tue Apr 19 06:52:11 2022 from 76.24.253.1
datalad@26696 ~ % python3 -c 'import platform; print(platform.machine())'
arm64

datalad@26696 ~ % grep wodder .ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAA....SENSORED...p+YA1nXDTIAaXVdZRRcJ3IU1 jwodder@Johns-MacBook-Pro.local

```

**Comment by jwodder** [comment]
@yarikoptic To be clear, should Rosetta be installed whenever git-annex is being installed, regardless of method, or only for certain methods?

**Comment by yarikoptic** [comment]
I don't know if that would work for brew, so may be let's limit to all those which install .dmg
