### ISSUE TITLE
Figure out how to install Miniconda on Windows via Python

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-installer#16]
Goal: A Python function meeting the following specifications:

* It must take two arguments:
    * `installer_path`, a `pathlib.Path` object (possibly relative) pointing to a locally-downloaded copy of https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
    * `miniconda_path`, a `pathlib.Path` object (possibly relative) giving the location of a directory (which does not yet exist) at which Miniconda should be installed
* The function must run the script at `installer_path` with the result that Miniconda is installed at `miniconda_path`, without the user being prompted for any input
* Bonus: A variant of this function that does prompt the user for input but sets the (default) path at which to install Miniconda to `miniconda_path`

The closest I've been able to get is:

```python
from pathlib import Path
import subprocess

miniconda_dir = Path("foo").resolve()
miniconda_dir.mkdir()

subprocess.run(
    f'start /wait "" Miniconda3-latest-Windows-x86_64.exe /S /D={miniconda_dir}',
    shell=True,
    check=True,
)
```

However, after successfully running this script a couple times, and then unsuccessfully running some variants, re-running the original script resulted in the `subprocess.run()` doing nothing, and I have no idea why.

**Comment by yarikoptic** [comment]
`Path("foo").resolve()` seems to not resolve to full path, and I just end up without anything installed... when I specified full path (did everything in "cmd line") it worked , so try with `Path("foo").resolve()` ?

**Comment by jwodder** [comment]
@yarikoptic 

> `Path("foo").resolve()` seems to not resolve to full path

Interesting.  The failure to resolve when `foo` doesn't exist seems to be Windows-specific.  Fortunately, creating `foo` first seems to be sufficient to get the script to work.

> `Path("foo").absolute()`

No such method.

**Comment by yarikoptic** [comment]
> 
> > `Path("foo").absolute()`
> 
> No such method.

hm... indeed https://docs.python.org/3.8/library/pathlib.html doesn't list any but when I did in python console within pycharm:

```
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)] on win32
>>> from pathlib import Path
>>> Path('foo').absolute()
WindowsPath('C:/Users/DataLad/PycharmProjects/datalad/foo')
```

and then on laptop
```
(git)lena:~[master]
$> python3 -c 'from pathlib import Path; print(Path("a").absolute())'
/home/yoh/a
```
