### ISSUE TITLE
pip component guessing wrong bin path on GitHub Actions Ubuntu images

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-installer#18]
When `datalad-installer datalad -m pip` is run on a GitHub Actions Ubuntu image, the script will assume that the `datalad` command gets installed at `/usr/local/bin/datalad`.  This is wrong; apparently, it's installed somewhere else.  This results in the wrong path being printed out at the end of the script's run and in [this check](https://github.com/datalad/datalad-installer/blob/877d085fd53700d444ca6d78af0352248a1ea3e3/src/datalad_installer.py#L604) failing, resulting in the script exiting with status 1.

**Comment by yarikoptic** [comment]
without options given to `pip`, shouldn't it install "wherever `pip` is" ? (e.g. systemwide, venv, or conda env) and we do not need to do anything extra and assume any specific path and just rely on `datalad` after that be present somewhere along `$PATH`?

**Comment by jwodder** [comment]
A quick check shows that `python`, `pip`, and programs installed by `pip` on GHA Ubuntu images are located under `/opt/hostedtoolcache/Python/$PYTHON_VERSION/x64/bin/`, where `$PYTHON_VERSION` includes the micro/patch version level.
