### ISSUE TITLE
add --sudo=(ask|error|ok) option?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#32]
ATM datalad-installer invokes some commands with `sudo` without prompting that it is about to do smth possibly lethal.  I think it would be nice to ask user a permission by default first, be able to error (if I am not expecting sudo to be ran), or just "ok" (e.g. on CI) runs.

**Comment by jwodder** [comment]
@yarikoptic

* What should the default value for this setting be?
* When the setting is "ask", should the script ask just once (before sudo is run for the first time) or before every time sudo is run?

**Comment by yarikoptic** [comment]
a nice feature would be if it allows for "[y]es|yes-[a]ll|[n]o" answer and if "yes-[a]ll" - not ask for the subsequent instances
