### ISSUE TITLE
Optimal use on HPC-like systems

### ISSUE THREAD

**Issue by mih** [datalad/datalad-installer#38]
I am trying to consolidate all installation instructions in the handbook to use the installer.

Starting with a conda-based installation, it is not immediately clear to me, what the optimal usage pattern would be. It seems the defaults are a bit geared towards one-off temporary deployments.

I would appreciate feedback on how to update the instructions, maybe starting with the HPC+conda case. Here is what we have right now:

```sh
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash Miniconda3-latest-Linux-x86_64.sh
# acknowledge license, keep everything at default
$ conda install -c conda-forge datalad
```

Can this be made more elegant, compact, or more flexible with direct installer use (assuming that an HPC env has Python 3.6+)?

Thx!

**Comment by jwodder** [comment]
The datalad-installer equivalent to those commands is (after installing datalad-installer, either with pip or via downloading the script directly):

```
datalad-installer conda --path where/to/place/conda datalad
```

**Comment by yarikoptic** [comment]
a slight correction:
```
datalad-installer miniconda --path where/to/place/conda datalad
```
I typically go for
```
datalad-installer -E where/to/place/conda.sh miniconda --path where/to/place/conda datalad
```
so I have the shell script I could right away `source` or do that in the `~/.profile`

**Comment by yarikoptic** [comment]
@mih, feel welcome to reopen if there is more to be done on this

**Comment by mih** [comment]
Thx! It will take me a moment to try things out.
