### ISSUE TITLE
Neurodebian not available in Ubuntu 20.04

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-installer#39]
The Ubuntu environment used for this repo's GitHub Actions has just been upgraded to Ubuntu 20.04, which does not have neurodebian in its apt repository.  As a result, the tests are failing on Ubuntu.

@yarikoptic What would be the preferred way to install NeuroDebian on 20.04?

**Comment by yarikoptic** [comment]
Thank you for the report... damn that I have missed that at the point of 20.04 debian most likely had no neurodebian in testing :-/ 

<details>
<summary>current whohas for debian and ubuntu. 20.04 is focal</summary> 

```shell
$> whohas -D Debian,Ubuntu --strict neurodebian                                                    
Debian      neurodebian                            0.37.6             34K             all                       http://packages.debian.org/stretch/neurodebian
Debian      neurodebian                            0.38.3             33K             all                       http://packages.debian.org/buster/neurodebian
Debian      neurodebian                            0.41.0             34K             all                       http://packages.debian.org/bullseye/neurodebian
Debian      neurodebian                            0.41.0             34K             all                       http://packages.debian.org/sid/neurodebian
Ubuntu      neurodebian                            0.37.2             27K             all                       http://packages.ubuntu.com/xenial/neurodebian
Ubuntu      neurodebian                            0.37.2ubuntu1      25K             all                       http://packages.ubuntu.com/xenial-updates/neurodebian
Ubuntu      neurodebian                            0.37.6             28K             all                       http://packages.ubuntu.com/bionic/neurodebian
Ubuntu      neurodebian                            0.40.1             27K             all                       http://packages.ubuntu.com/groovy/neurodebian
Ubuntu      neurodebian                            0.41.0             27K             all                       http://packages.ubuntu.com/hirsute/neurodebian

```
</details>

unfortunately AFAIK there is no clean way to add neurodebian to stock 20.04 now. To avoid custom code (e.g. following minimal installation instructions from neuro.debian.net) for alternative "enabling neurodebian", I think the best would be to just download neurodebian package backport.  Since version could change on http://neuro.debian.net/debian/pool/main/n/neurodebian/, I guess we should just use http://snapshot-neuro.debian.net/ , and just download and `dpkg -i` 

- http://snapshot-neuro.debian.net/archive/neurodebian/20210221T060502Z/pool/main/n/neurodebian/neurodebian-archive-keyring_0.41.0~nd20.04%2B1_all.deb
- http://snapshot-neuro.debian.net/archive/neurodebian/20210221T060502Z/pool/main/n/neurodebian/neurodebian-popularity-contest_0.41.0~nd20.04%2B1_all.deb
- http://snapshot-neuro.debian.net/archive/neurodebian/20210221T060502Z/pool/main/n/neurodebian/neurodebian_0.41.0~nd20.04%2B1_all.deb

?

**Comment by jwodder** [comment]
@yarikoptic

> To avoid custom code (e.g. following minimal installation instructions from neuro.debian.net)

What's so bad about those instructions?  As far as I can tell, the worst part is that datalad-installer's sudo confirmation check currently isn't set up to show the user the contents of the file being added to `sources.list.d`.

**Comment by yarikoptic** [comment]
They also don't choose optimal mirror for you (like installer does), have no options to enable devel repository, (may be there is more to it). Altogether - they aren't that bad, but we probably should have it consistent across Debian/Ubuntu releases

**Comment by yarikoptic** [comment]
But hold on, indeed, we can just add repository manually (of not yet known according to apt policy) and then proceed normally to install NeuroDebian package... May be done option/envvar would need to be set to alter to override existing config

**Comment by jwodder** [comment]
@yarikoptic So the script *should* follow the instructions from the website?

> May be done option/envvar would need to be set to alter to override existing config

What config are you referring to?

**Comment by yarikoptic** [comment]
> @yarikoptic So the script _should_ follow the instructions from the website?

yes, let's try that: do
```
wget -O- http://neuro.debian.net/lists/focal.us-nh.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
```
before proceeding to install `neurodebian` package

Ideally we should not do that "just for focal" but implement it so it does it for any release where `neurodebian` is not available:

<details>
<summary>odd that apt policy returns with 0 even if no package found :-/ </summary> 

```shell
root@b55708239a06:/# apt-cache policy neurodebian
N: Unable to locate package neurodebian
root@b55708239a06:/# echo $?
0
root@b55708239a06:/# apt policy neurodebian
N: Unable to locate package neurodebian
root@b55708239a06:/# echo $?
0
```
</details>

<details>
<summary>but apt install --no-act neurodebian could be used</summary> 

```shell
root@b55708239a06:/# apt install --no-act neurodebian
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package neurodebian
root@b55708239a06:/# echo $?
100

```
</details>

but figuring out for which release to get that configuration from the web requires parsing of `apt policy` output, see e.g. https://github.com/neurodebian/neurodebian/blob/HEAD/tools/nd-configurerepo#L435

or do you see a better way to figure it out (we would need it even know to know which file to download, cannot just hardcode focal)?

> > May be done option/envvar would need to be set to alter to override existing config
> 
> What config are you referring to?

`NEURODEBIAN_OVERWRITE`

https://github.com/neurodebian/neurodebian/blob/HEAD/tools/nd-configurerepo#L35

**Comment by jwodder** [comment]
@yarikoptic The name of the release can be retrieved by running `lsb_release -cs`.
