### ISSUE TITLE
Provide target path or more convenient way to determine one

### ISSUE THREAD

**Issue by mih** [datalad/datalad-installer#47]
I need to use an `autobuild` git-annex in a CI run. I failed to find a convenient way to either indicate or determine, where the installer would put `git-annex`. I ended up doing something like

```
export PATH=$(dirname ${TMPDIR}/dl-build*/git-annex*/git-annex):$PATH
```

But I would be more confident if I would be able to instruct the installer where to place binaries.

**Comment by jwodder** [comment]
If all you need is to set the `PATH` appropriately after installing, you can specify a filepath with the `--env-write-file` global option and then source that file after running the script.

**Comment by mih** [comment]
Cool! I did not make that connection.

I assume that is a POSIX file?

**Comment by jwodder** [comment]
@mih It should be sourceable by any Bourne-compatible shell.

**Comment by mih** [comment]
Cool thx!
