### ISSUE TITLE
windows: git-annex installation seemed to work but "cannot execute program!" message

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#48]
```shell
(datalad-container-try) C:\Users\DataLad\PycharmProjects>python datalad\tools\which.py git
C:\Program Files\Git\cmd\git.exe

(datalad-container-try) C:\Users\DataLad\PycharmProjects>pip install datalad-installer
Collecting datalad-installer
  Downloading datalad_installer-0.3.0-py3-none-any.whl (20 kB)
Installing collected packages: datalad-installer
Successfully installed datalad-installer-0.3.0

(datalad-container-try) C:\Users\DataLad\PycharmProjects>datalad-installer git-annex
2021-03-23T11:01:34-0700 [INFO    ] datalad_installer Writing environment modifications to C:\Users\DataLad\AppData\Local\Temp\dl-env-59c6tjmj.sh
2021-03-23T11:01:34-0700 [INFO    ] datalad_installer Installing git-annex via datalad/packages
2021-03-23T11:01:34-0700 [INFO    ] datalad_installer Version: None
2021-03-23T11:01:34-0700 [INFO    ] datalad_installer Downloading https://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe
2021-03-23T11:01:37-0700 [INFO    ] datalad_installer Running: 'C:\Users\DataLad\AppData\Local\Temp\dl-datalad-package-z9ngm4qv\git-annex-installer_latest-snapshot_x64.exe' /S
2021-03-23T11:01:38-0700 [INFO    ] datalad_installer Operation requires elevation; rerunning as administrator
2021-03-23T11:01:38-0700 [INFO    ] datalad_installer Running as administrator: C:\Users\DataLad\AppData\Local\Temp\dl-datalad-package-z9ngm4qv\git-annex-installer_latest-snapshot_x64.exe /S
2021-03-23T11:01:42-0700 [INFO    ] datalad_installer git-annex is now installed at C:\Program Files\Git\usr\bin\git-annex.exe
2021-03-23T11:01:42-0700 [ERROR   ] datalad_installer Cannot execute program!
```

and resulted in
```
(datalad-container-try) C:\Users\DataLad\PycharmProjects>git annex version
git-annex version: 8.20210128-g4407ade4c
build flags: Assistant Webapp Pairing TorrentParser MagicMime Feeds Testsuite S3 WebDAV
...

```

so seems to be ok... but not clear which program it failed to execute (ERROR message should be improved).  Also it might relating to the fact that
```
(datalad-container-try) C:\Users\DataLad\PycharmProjects>python datalad\tools\which.py git-annex
```
came out empty -- so there is no `git-annex` in the PATH, but somehow in miniconda shell it is just doing automagic rewrite of my invocation if I ask for `git-annex version`:

```shell
(datalad-container-try) C:\Users\DataLad\PycharmProjects>git-annex version

(datalad-container-try) C:\Users\DataLad\PycharmProjects>git annex version
git-annex version: 8.20210128-g4407ade4c
...
```
so if it is a matter of a check, may be just check for `git annex` not `git-annex`?  I think it should be good enough for datalad.

**Comment by jwodder** [comment]
@yarikoptic The error message means that the `os.access(path, os.X_OK)` check failed on `git-annex.exe`.  I don't know enough about to Windows to know how reasonable such a check is there, but I don't recall encountering such an error when I tested the `datalad/packages` installation method.

**Comment by yarikoptic** [comment]
in any case error message should be improved to clearly reflect the check, e.g. here it could be  "Expected {path} is not found" or "{path} is not executable".  But in particular for this Windows installation intricacy I wonder if we could check running that command in some "exemplar" invocation, e.g. `git annex version` here?

**Comment by jwodder** [comment]
@yarikoptic Do you want that to replace the `os.access()` check for the `datalad/packages` installation method only?

**Comment by yarikoptic** [comment]
I am not sure ... indeed looks like a windows + git-annex (datalad/packages) specific gotcha ATM but I think it is applicable to all components that installation should result in some new "command" (could be a direct executable like `git-annex` or `git annex`) to become available, and thus a check might indeed vary across components.

**Comment by yarikoptic** [comment]
Since it seems we know where executable is made available (`git-annex is now installed at C:\Program Files\Git\usr\bin\git-annex.exe`) and we do adjust the `PATH` for subsequent invocations IIRC, I think it could be "universal" across components (not just `datalad`) and just need to prescribe the command to be ran to do the test. Actually I think they all should handle `--help`, so could be `git annex --help`, `conda --help`, `datalad --help`?

**Comment by yarikoptic** [comment]
ping @jwodder on this

**Comment by jwodder** [comment]
@yarikoptic What exactly do you want me to do for this?

**Comment by yarikoptic** [comment]
on windows -- skip testing for excitability (`os.access(path, os.X_OK)`)  since I am not sure if we can rely on it, on any system - complement with a check executing the sample command (e.g. `--help`) while providing full path to it in that location.

**Comment by jwodder** [comment]
@yarikoptic Exactly what do you want `--help` run for?  Currently, the code only recognizes `git-annex` and `datalad` as installed commands, and it would take nontrivial rewrites for `conda` to be recognized as an installed command.

**Comment by yarikoptic** [comment]
So let's do for git-annex and datalad only
