### ISSUE TITLE
Facilitate rapid releasing  by adding auto

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#5]

**Comment by jwodder** [comment]
I'm going to hold off on this until after there's a final (non-alpha) release, as `auto` does not produce PEP 440-compatible prerelease version strings.

**Comment by yarikoptic** [comment]
IMHO it is already worth of 0.1.0 release -- we use it daily ;)

**Comment by jwodder** [comment]
Version 0.1.0 released.  I'll set up `auto` later; the need for this to be a single standalone file prevents us from using `versioneer` or the like, so I'll need to figure out how to get `auto` to update the version number in the source file.
