### ISSUE TITLE
it seems we might need an explicit brew update before brew install git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#52]
see https://github.com/Homebrew/homebrew-core/issues/75243#issuecomment-820482307

not sure if we should unconditionally do `brew update` before any install to follow, or do it as a mediation step if initial `brew install` fails, or somehow detect if it is needed.  I will let you @jwodder to decide on that.  unconditional `brew update` if any install to follow sounds like the easiest.

**Comment by jwodder** [comment]
@yarikoptic Please merge #51 first in order to avoid a future merge conflict.
