### ISSUE TITLE
Pip script install path determination broken by pip 21.1

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-installer#62]
[The code for determining the install location of executables installed with pip](https://github.com/datalad/datalad-installer/blob/f7f0aaf6f4a5198b93c671109bc8c3e70f186690/src/datalad_installer.py#L1392-L1399) no longer works under pip 21.1.  My current attempts to update the code are failing because the new function is returning `"."` despite the executables not being installed in the current directory.

Also, the CI test that installs the latest development version of pip does not work, as the only tests that use pip install inside a virtual environment and thus ignore whatever version of pip is installed outside the venv.

**Comment by yarikoptic** [comment]
so it is a bug or intended change in `pip`?  Might be worth clarifying with `pip` folks?

**Comment by jwodder** [comment]
@yarikoptic It's an intended change in pip.

**Comment by yarikoptic** [comment]
do you have ideas on how to workaround/fix?  if I get it correctly, that is what renders our CI red ATM.  Do you think e.g. it would be feasible to update to pip only prior 21.1 for now to provide short term mitigation while we are coming up with a proper solution?

**Comment by jwodder** [comment]
@yarikoptic I think I've gotten the code to work properly on the latest pip now.  I'm just waiting for the tests to finish running.
