### ISSUE TITLE
how to get "alerted" on cron job fails?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#64]
reflecting on #62 and cron fails of https://github.com/datalad/datalad-installer/actions - I am subscribed to repo, but was not alerted on any of those ? I do get alerts whenever datalad/git-annex workflows fail.  Anything for me to configure or somewhere in the actions (forgot)

**Comment by jwodder** [comment]
@yarikoptic If GitHub Actions isn't sending you e-mails (and I don't understand how it determines whom to e-mail), it appears that the only option is to add an explicit step to the workflow for sending e-mails on failure, [like this](https://github.com/datalad/git-annex/blob/4419606460291b34d30a775b8f9bad1d12d6d1b9/.github/workflows/build-ubuntu.yaml#L165-L179).

**Comment by yarikoptic** [comment]
FTR: I seems to receive some notifications but not all... unless I removed by mistake I see the last one from
```
Jul 26 Yaroslav Halche *-6.8* ( 71K/0) [datalad/datalad-installer] Run failed: Test - master (bb62984) 
```
whenever 
https://github.com/datalad/datalad-installer/actions lists failed 504 run (https://github.com/datalad/datalad-installer/actions/runs/1111783621) from yesterday (Aug 09)... I guess will check again later again
