### ISSUE TITLE
conda-forge feedstock

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#70]
Let's make that one as well please -- would assist in making git-annex available through conda without invoking pip.

**Comment by jwodder** [comment]
@yarikoptic Conda-forge PR: https://github.com/conda-forge/staged-recipes/pull/15317

**Comment by yarikoptic** [comment]
feedstock merged now and there is even https://anaconda.org/conda-forge/datalad-installer so -- resolved
