### ISSUE TITLE
provide an alternative to 'dpkg -i' mechanism to "install" git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#71]
users might not be able to `dpkg -i` if they aren't admins, and it might simply be not desirable (e.g. just to test the bleeding edge build we prepare/ship as .deb).  But our datalad/git-annex build is the bleeding edge one and `snapshot` builds from git-annex could be dated.

So as outlined in https://github.com/datalad/datalad/issues/5750#issuecomment-863417163 it is easy to just `dpkg -x` (instead of `dpkg -i`) the .deb and then adjust the environment file to have PATH point under `<extraced_tmp_dir>/usr/lib/git-annex.linux` so very similar to what is done for `snapshot` method of installation.

Thus I think it would be nice to have some option which would allow for methods which download .deb to be able to say to not `dpkg -i` but rather "extract and adjust PATH".  didn't look into either it is generic or specific to git-annex, so will leave to you @jwodder to decide on what would be the best way to interface it.

**Comment by jwodder** [comment]
@yarikoptic The `deb-url` installer can install both git-annex and datalad.  Where in a datalad .deb file is the bin directory located?

**Comment by yarikoptic** [comment]
not sure if it would be usable for datalad package, didn't test.  To make it work it would need not only PATH  but also PYTHONPATH tune up, but even then I am afraid it might not work reliably since it might still pick up entry points from possibly system wide installed datalad. I would limit this to `git-annex` for now.  Location for that is in the original description (`<extraced_tmp_dir>/usr/lib/git-annex.linux`)

**Comment by jwodder** [comment]
@yarikoptic Inspecting an actual `.deb` from the latest datalad/git-annex release shows that the actual bin directory is `usr/lib/git-annex.linux/bin`, and the `git-annex` file within is symlinked to `usr/bin`.  Couldn't I just use `usr/bin`?

**Comment by yarikoptic** [comment]
I think `usr/bin` should work but never tried that way -- always was just tuning PATH to use `<extraced_tmp_dir>/usr/lib/git-annex.linux`. Note: that `bin/` under `<extraced_tmp_dir>/usr/lib/git-annex.linux` is "no good" for direct use.
