### ISSUE TITLE
Installing to miniconda inside another conda environment fails

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-installer#74]
It appears that running `datalad-installer miniconda datalad` when an outer conda environment is already in effect causes datalad to be installed to the outer environment instead of to the miniconda created by datalad-installer.  This results in the check that the datalad executable is in the expected location failing, and this in turn is responsible for the test failures of the datalad-installer recipe on conda-forge.

@yarikoptic Do you know a way around this?

**Comment by yarikoptic** [comment]
For now may be for `miniconda` just let's check if we are already having `conda` executable (ie already in conda) and if so -- error out.  And skip any corresponding test if that is the case.   Later (whenever user expresses desire) we could look into what is really causing using base env -- might be `conda` itself not allowing for having multiple `conda` in the `PATH` and confusing things up

**Comment by jwodder** [comment]
@yarikoptic Just testing whether a `conda` executable is in `PATH` means that the miniconda tests (which are most of the install tests) will now not work on GitHub Actions.  The better option would be to test whether Conda is active; how would I do that?

**Comment by yarikoptic** [comment]
do you mean that `conda` is already installed by default in github actions environment?
then I guess we could either 
- indeed just mark the tests like you did in  https://github.com/datalad/datalad-installer/pull/78/commits/3c25472c80e65acba47314bbd35f44011772ed42 and exclude them from running in feedstock
- from PATH strip away all paths which provide `conda` before running tests

**Comment by jwodder** [comment]
@yarikoptic

> do you mean that conda is already installed by default in github actions environment?

Yes.

Is there not an environment variable we could check for or a query we could make to `conda info` to check whether a conda environment is currently active?

**Comment by jwodder** [comment]
@yarikoptic It appears that `CONDA_PREFIX` is the envvar to check for.
