### ISSUE TITLE
windows: causes doesn't automagically elevate

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#82]
sorry -- copy/paste from terminal didn't workout from virtualbox for some reason

![image](https://user-images.githubusercontent.com/39889/127044544-f263f712-7b1c-4529-baf4-0d1a88dcce05.png)

IMHO it should have worked -- anything we could do?

**Comment by jwodder** [comment]
@yarikoptic I was under the impression that the given command should work without elevation.  If it requires it, I can make the command run always elevated.

**Comment by yarikoptic** [comment]
can on windows we have some generic (for this and other commands as we encounter) helper, e.g. `run_maybe_elevated`: run without elevation, if WinError 740 -- elevate (with all the `--sudo` option logic)?
