### ISSUE TITLE
dpkg --remove --ignore-depends=git-annex git-annex (if installed) before installing git-annex-standalone deb

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#99]
Was trying to update git annex to fresh build from datalad/git-annex but that failed due to

```
$> src/datalad_installer.py git-annex -m datalad/git-annex
...
About to run the following command as an administrator:
    dpkg -i '/home/yoh/.tmp/tmp4cg2zkax/git-annex-standalone_8.20211231+git126-gf7a3c1355-1~ndall+1_amd64.deb'
Proceed? [y/a/n] y
2022-01-24T10:13:11-0500 [INFO    ] datalad_installer Running: sudo dpkg -i '/home/yoh/.tmp/tmp4cg2zkax/git-annex-standalone_8.20211231+git126-gf7a3c1355-1~ndall+1_amd64.deb'
[sudo] password for yoh: 
Selecting previously unselected package git-annex-standalone.
dpkg: regarding .../git-annex-standalone_8.20211231+git126-gf7a3c1355-1~ndall+1_amd64.deb containing git-annex-standalone:
 git-annex-standalone conflicts with git-annex
  git-annex (version 8.20211123-1) is present and installed.
```

I think the right way to handle this would be to check first if `git-annex` ( not `git-annex-standlone`) is installed, and if it is -- uninstall it explicitly first and then proceed to `dpkg -i`

**Comment by jwodder** [comment]
@yarikoptic
* Should this be done for just the datalad/git-annex and datalad/git-annex:tested methods or also the deb-url method?
* I assume this should not be done when installing a .deb into a specific target directory rather than system-wide, correct?
